# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

env:
    AI_XXX: hello world

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        environment: production # must same with repo -> settings -> environments
        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Run tests
              env:
                  CLOUDFLARE_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_AUTH_TOKEN }}
                  CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
              run: |
                  echo "$CLOUDFLARE_ACCOUNT_ID"
                  deno test -A cf_ai_test.ts
